### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by nori8nori** [nori8nori/furima_28719#9]
【自身のフリマアプリのURL】
https://furima-28719.herokuapp.com/

【Basic認証のIDとパスワード】
ID:admin
PW:2222

【出品者用のメールアドレスとパスワード】
メール：hanako@gmail.com
PW:hanako88

【購入者のメールアドレスとパスワード】
メール：tarou@gmail.com
PW：tarou88

【購入用カードの番号・期限・セキュリティコード】
カード情報：4242424242424242
有効期限：2月22年
セキュリティーコード：123

**Comment by tcamp1234** [comment]
nori8nori さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by nori8nori** [comment]
ご確認いただきありがとうございます。
これからも全力で学習に励みます。
